services:
  prometheus:
    image: prom/prometheus:latest
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.enable-admin-api"
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    networks:
      - monitoring

  node-exporter:
    image: prom/node-exporter:latest
    command:
      - "--path.rootfs=/host"
    volumes:
      - /:/host:ro,rslave
    networks:
      - monitoring

  prometheus-snapshot-manager:
    image: ghcr.io/f18m/prometheus-snapshot-manager:latest
    volumes:
      # config
      - ./config.example.yaml:/etc/prometheus-snapshot-manager/config.yaml:ro
      # data to backup -- needs rw to allow for snapshot archive creation&deletion (transient file)
      - prometheus_data:/prometheus:rw
      # backup destination:
      - ./backup/prometheus:/backup/prometheus:rw
    environment:
      - SFTP_PASSWORD=mysecretpassword
      - AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
    networks:
      - monitoring
    restart: unless-stopped
    depends_on:
      - prometheus
      - node-exporter

volumes:
  prometheus_data:

networks:
  monitoring:
    driver: bridge
